### ISSUE TITLE
Uuid factory issue with Laravel ^8

### ISSUE THREAD

**Issue by steveerg** [lucadello91/eloquent-uuid#8]
Packages version:
- laravel 8.54
- lucadello91/eloquent-uuid 1.3

During a test i've got error **PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: registrations.id** asserting the model was correctly created from factory class. It seems UUID is not automatically generated nor if i force in the factory class the generation with "id" => $this->factory->uuid.

```
$registration = Registration::factory([
            'status' => RegistrationStatusEnum::ACCEPTED(),
])->createQuietly();

$this->assertModelExists($registration);
```

Registration model factory

```
return [
            'business_name' => $this->faker->company,
            'vat_number'    => $this->faker->bothify('##????????????????'),
            'fiscal_code'   => $this->faker->bothify('##????????????????'),
            'first_name'    => $this->faker->firstName,
            'last_name'     => $this->faker->lastName,
            'email'         => $this->faker->safeEmail(),
            'type'          => $this->faker->randomElement(CustomerTypeEnum::toValues()),
            'status'        => $this->faker->randomElement(RegistrationStatusEnum::toValues()),
];
```

Registration model

```
class Registration extends Model
{
    use HasFactory, UuidModelTrait, Notifiable;
    
    protected $fillable = [
        'business_name',
        'first_name',
        'last_name',
        'fiscal_code',
        'vat_number',
        'email',
        'type',
        'status',
    ];

...
```

My workaround is to generate the registration from factory class forcing uuid as a params.

```
$registration = Registration::factory([
    'id'     => Str::uuid()->toString(),
    'status' => RegistrationStatusEnum::ACCEPTED(),
])->createQuietly();
```

and forcing **public $incrementing = false;** in the model.

**Comment by lucadello91** [comment]
The Uuid was not generated because of `->createQuietly();` that block events on model.

The Uuid is generated in 'creating' event.

Thanks for using this package.
Regards
Luca
